# Generated by Django 4.2.4 on 2024-08-21 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='')),
                ('time_start', models.DateTimeField()),
                ('date', models.DateField()),
                ('transcript', models.TextField()),
                ('entities', models.TextField()),
                ('keywords', models.TextField()),
                ('summary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
