# Generated by Django 5.1 on 2024-08-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='entities',
            new_name='speaker',
        ),
        migrations.RenameField(
            model_name='clip',
            old_name='transcript',
            new_name='transcription',
        ),
        migrations.RenameField(
            model_name='clip',
            old_name='author',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='clip',
            name='duration',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='score',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='time_end',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
