# Generated by Django 5.1 on 2024-08-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_alter_clip_duration_alter_clip_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='speaker',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
