# Generated by Django 4.2.4 on 2024-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Report', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
