# Generated by Django 4.2.4 on 2024-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_title_alter_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportobjective',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
